language: java
jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "ferzerkerx-github"
    token:
      secure: "WnTDUnLoYOIALu5jTSehKub4w72AgSGdZwlVR26iNpEpfiPQRRQ0IxtXwYToUlsglmuV5AAtl7If3TkzIO/hcTpw4yyw5LeytGDXMbupQ2aDDzDldFQRZPCAZLCS3GKMpRjp4lr3mux4MnletTpkuGsQunZ1lq8VQx9Dp+SW4aZEWcqGJKBelyoDSxfydaM2EMa44/iPvX+6LJso1nbj5CK2DFX0AM1odPNwacbmqz/26otCQ8F+MhbAICECFuLuFW8qqlUMwl1nV/9km0sUT1pMDxbJrwArFp6pHCH5P4Q30vJOX3C0isSQEVlP+zIRKw9/eS4uoq2BjukVowEWywdOsoZGS7Dnj/7a7u2fvctzQmhOaM/HIMXr34CzLYr4b5C6nV/ZARKAwGf9dlsgwbyajjgIC2cVV7Ovo8K2ORMPobMZKE5GfqoMU/5iZVjlOa6mMf/8UG7YwBc6wiB5yRRoZLW24+/U/cb/mTt7tId2CXCo03lW85Uj40gv5QmBpAEizqguVwMce5CU5dpmzzslRBAcy9teBU6KtDO948VWPXBlKCoguQ2uWvRlwAadDL3IWSoeTXstJc33q4czvKEc0b1gC860gjPewtsvePB7UM1R4H8U/4iDvaY04kqJkb/jh2S30kuBjJu6LnntLomszh+oGjGqsm2dB9kF0qo="
env:
  secure: "cIKi46jTfz0B9fs8xaOvLTwk787Sr5F1ZIrQ/b4BgyQ4nyTL2zwOmvISoPL6RHxKPC2jVU6RNGuzzW8hckXKhlxjfSxg689Dnf5HJfRYDZsux7rKQoe0s+wajopiMOJUDRk7iUc1UAu/M/NjBh5eP322/qh5MsLUZVLRxQxB4Kb82yRSK65dDJIFIDyp3gqJG5J13i2tZBREwzEw6PQ3RVCO7xVq4g//IwWh6N72MSN7jh7ETV5d8gdNLQEE3SIxUpU8tdnmhLScYzdFoEb2+GbMWTnqfLQgOLHO+Wn0KPIAuPVmeULChjIaOEHpAgRHPeJlW6ZHqkMV0mWshTwDBVCCbcSKMtdnxTiqzvyYzLEwkBNZkeDdmQ4LhBVpGnY7d9aGC3We+rb3WG7xoNrlYsaorDru8ugTLeH8xqsVU38QRErkWRC2amoEV65W5lSga7QO0u5aMaDEShoXWUdVQPzkYw7zYtpdLYmg8vVqCipZntOxEj+Ujk9WKzcPnkFHE68hUhcSy21JtfPtFU2Zj6qt7KObmD2wpTCjaxXvXMnAZUlEvyXTcI4rv3H+PYwOmIKhTDDXS2gtWbyhL2Wma36Lf9imNI9LRTWocIiSwUkjWLuNy45bTIofplHdyp+2DUTTsWeSXPmMZ+19wshlhfyqzaEyOzq+xPBk+0W7k+E="

install:
  - "mvn clean compile"
  - "npm install -g snyk"

script:
  - "mvn -Dmaven.test.failure.ignore=false org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar"

after_success:
  - snyk monitor
